# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ayarlar(object):
    def setupUi(self, Ayarlar):
        Ayarlar.setObjectName("Ayarlar")
        Ayarlar.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(Ayarlar)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(40, 35, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(260, 30, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 100, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 170, 141, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(300, 240, 61, 41))
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton.setGeometry(QtCore.QRect(400, 310, 91, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 10, 141, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(40, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 60, 141, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(40, 150, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 110, 141, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(40, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(250, 160, 141, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(40, 200, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(250, 210, 141, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(40, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton.setGeometry(QtCore.QRect(230, 260, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 260, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(30, 290, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 280, 61, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(370, 320, 121, 41))
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(20, 320, 91, 41))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(280, 80, 161, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 180, 75, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab_4)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(400, 300, 91, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(70, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(70, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(252, 70, 151, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(70, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(250, 130, 151, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(70, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_3.setGeometry(QtCore.QRect(220, 210, 82, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_4.setGeometry(QtCore.QRect(360, 210, 82, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 270, 75, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.tab_5)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(400, 310, 91, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.tabWidget.addTab(self.tab_5, "")
        Ayarlar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ayarlar)
        self.statusbar.setObjectName("statusbar")
        Ayarlar.setStatusBar(self.statusbar)

        self.retranslateUi(Ayarlar)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Ayarlar)
        Ayarlar.setTabOrder(self.tabWidget, self.lineEdit)
        Ayarlar.setTabOrder(self.lineEdit, self.lineEdit_2)
        Ayarlar.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Ayarlar.setTabOrder(self.lineEdit_3, self.pushButton)
        Ayarlar.setTabOrder(self.pushButton, self.commandLinkButton)
        Ayarlar.setTabOrder(self.commandLinkButton, self.lineEdit_4)
        Ayarlar.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Ayarlar.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        Ayarlar.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Ayarlar.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        Ayarlar.setTabOrder(self.lineEdit_8, self.radioButton)
        Ayarlar.setTabOrder(self.radioButton, self.radioButton_2)
        Ayarlar.setTabOrder(self.radioButton_2, self.pushButton_3)
        Ayarlar.setTabOrder(self.pushButton_3, self.commandLinkButton_5)
        Ayarlar.setTabOrder(self.commandLinkButton_5, self.commandLinkButton_4)
        Ayarlar.setTabOrder(self.commandLinkButton_4, self.comboBox)
        Ayarlar.setTabOrder(self.comboBox, self.pushButton_2)
        Ayarlar.setTabOrder(self.pushButton_2, self.lineEdit_9)
        Ayarlar.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        Ayarlar.setTabOrder(self.lineEdit_10, self.radioButton_3)
        Ayarlar.setTabOrder(self.radioButton_3, self.radioButton_4)
        Ayarlar.setTabOrder(self.radioButton_4, self.pushButton_4)
        Ayarlar.setTabOrder(self.pushButton_4, self.commandLinkButton_3)
        Ayarlar.setTabOrder(self.commandLinkButton_3, self.commandLinkButton_2)

    def retranslateUi(self, Ayarlar):
        _translate = QtCore.QCoreApplication.translate
        Ayarlar.setWindowTitle(_translate("Ayarlar", "AYARLAR"))
        self.label_2.setText(_translate("Ayarlar", "Mevcut Şifreniz"))
        self.label_3.setText(_translate("Ayarlar", "Yeni Şifreniz"))
        self.label_4.setText(_translate("Ayarlar", "Yeni Şifreniz (Tekrar)"))
        self.pushButton.setText(_translate("Ayarlar", "ONAYLA"))
        self.commandLinkButton.setText(_translate("Ayarlar", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Ayarlar", "Şifre Değiştime"))
        self.label_5.setText(_translate("Ayarlar", "Ad"))
        self.label_7.setText(_translate("Ayarlar", "Soyad"))
        self.label_8.setText(_translate("Ayarlar", "Mail adres"))
        self.label_9.setText(_translate("Ayarlar", "Doğum Tarihi"))
        self.label_10.setText(_translate("Ayarlar", "Kullanıcı Adı"))
        self.label_11.setText(_translate("Ayarlar", "Cinsiyet"))
        self.radioButton.setText(_translate("Ayarlar", "Kadın"))
        self.radioButton_2.setText(_translate("Ayarlar", "Erkek"))
        self.label_12.setText(_translate("Ayarlar", "Fotoğraf Güncelleme"))
        self.pushButton_3.setText(_translate("Ayarlar", "ÇEK"))
        self.commandLinkButton_5.setText(_translate("Ayarlar", "GÜNCELLE"))
        self.commandLinkButton_4.setText(_translate("Ayarlar", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Ayarlar", "Bilgi Güncelleme"))
        self.label_6.setText(_translate("Ayarlar", "Sileceğiniz Hesabı Seçiniz"))
        self.comboBox.setItemText(0, _translate("Ayarlar", "Mevcut Hesap"))
        self.pushButton_2.setText(_translate("Ayarlar", "SİL"))
        self.commandLinkButton_2.setText(_translate("Ayarlar", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Ayarlar", "Hesap Silme"))
        self.label_13.setText(_translate("Ayarlar", "Günlük Limitlerinizi Belirleyiniz"))
        self.label_14.setText(_translate("Ayarlar", "EFT"))
        self.label_15.setText(_translate("Ayarlar", "HAVALE"))
        self.label_17.setText(_translate("Ayarlar", "E-TİCARET"))
        self.radioButton_3.setText(_translate("Ayarlar", "Açık"))
        self.radioButton_4.setText(_translate("Ayarlar", "Kapalı"))
        self.pushButton_4.setText(_translate("Ayarlar", "ONAYLA"))
        self.commandLinkButton_3.setText(_translate("Ayarlar", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Ayarlar", "Limit Ayarları"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ayarlar = QtWidgets.QMainWindow()
    ui = Ui_Ayarlar()
    ui.setupUi(Ayarlar)
    Ayarlar.show()
    sys.exit(app.exec_())
