# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bağış.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bagis(object):
    def change_page(self):
        self.tabWidget.setCurrentIndex(1)

    def setupUi(self, Bagis):
        Bagis.setObjectName("Bagis")
        Bagis.resize(489, 399)
        self.centralwidget = QtWidgets.QWidget(Bagis)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton.setGeometry(QtCore.QRect(0, 80, 185, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton.clicked.connect(self.change_page)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(0, 130, 185, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_2.clicked.connect(self.change_page)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(0, 180, 185, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_3.clicked.connect(self.change_page)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(0, 230, 185, 41))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_4.clicked.connect(self.change_page)
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(0, 280, 201, 41))
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.commandLinkButton_5.clicked.connect(self.change_page)
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_6.setGeometry(QtCore.QRect(0, 330, 185, 41))
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.commandLinkButton_6.clicked.connect(self.change_page)
        self.commandLinkButton_7 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_7.setGeometry(QtCore.QRect(500, 400, 185, 41))
        self.commandLinkButton_7.setObjectName("commandLinkButton_7")
        self.commandLinkButton_7.clicked.connect(self.change_page)
        self.commandLinkButton_8 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_8.setGeometry(QtCore.QRect(400, 320, 91, 41))
        self.commandLinkButton_8.setObjectName("commandLinkButton_8")
        self.commandLinkButton_8.clicked.connect(self.change_page)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(60, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(60, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(200, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 110, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(200, 220, 141, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(70, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(70, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 160, 61, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(240, 300, 61, 41))
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton_9 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton_9.setGeometry(QtCore.QRect(400, 320, 91, 41))
        self.commandLinkButton_9.setObjectName("commandLinkButton_9")
        self.tabWidget.addTab(self.tab_2, "")
        Bagis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Bagis)
        self.statusbar.setObjectName("statusbar")
        Bagis.setStatusBar(self.statusbar)

        self.retranslateUi(Bagis)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Bagis)
        Bagis.setTabOrder(self.tabWidget, self.commandLinkButton)
        Bagis.setTabOrder(self.commandLinkButton, self.commandLinkButton_2)
        Bagis.setTabOrder(self.commandLinkButton_2, self.commandLinkButton_3)
        Bagis.setTabOrder(self.commandLinkButton_3, self.commandLinkButton_4)
        Bagis.setTabOrder(self.commandLinkButton_4, self.commandLinkButton_5)
        Bagis.setTabOrder(self.commandLinkButton_5, self.commandLinkButton_6)
        Bagis.setTabOrder(self.commandLinkButton_6, self.lineEdit)
        Bagis.setTabOrder(self.lineEdit, self.lineEdit_2)
        Bagis.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Bagis.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Bagis.setTabOrder(self.lineEdit_4, self.textEdit)
        Bagis.setTabOrder(self.textEdit, self.pushButton)

    def retranslateUi(self, Bagis):
        _translate = QtCore.QCoreApplication.translate
        Bagis.setWindowTitle(_translate("Bagis", "BAĞIŞ"))
        self.label.setText(_translate("Bagis", "Bağış"))
        self.commandLinkButton.setText(_translate("Bagis", "AFAD"))
        self.commandLinkButton_2.setText(_translate("Bagis", "DARÜŞŞAFAKA"))
        self.commandLinkButton_3.setText(_translate("Bagis", "KIZILAY"))
        self.commandLinkButton_4.setText(_translate("Bagis", "LÖSEV"))
        self.commandLinkButton_5.setText(_translate("Bagis", "TSK MEHMETÇİK VAKFI"))
        self.commandLinkButton_6.setText(_translate("Bagis", "YEŞİLAY"))
        self.commandLinkButton_7.setText(_translate("Bagis", "GERİ"))
        self.commandLinkButton_8.setText(_translate("Bagis", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Bagis", "Seçim"))
        self.label_2.setText(_translate("Bagis", "Ad "))
        self.label_3.setText(_translate("Bagis", "Soyad"))
        self.label_4.setText(_translate("Bagis", "Tel.no"))
        self.label_5.setText(_translate("Bagis", "Not"))
        self.label_6.setText(_translate("Bagis", "Tutar"))
        self.pushButton.setText(_translate("Bagis", "GÖNDER"))
        self.commandLinkButton_9.setText(_translate("Bagis", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Bagis", "Bilgiler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bagis = QtWidgets.QMainWindow()
    ui = Ui_Bagis()
    ui.setupUi(Bagis)
    Bagis.show()
    sys.exit(app.exec_())
