# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fatura.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fatura(object):
    def setupUi(self, Fatura):
        Fatura.setObjectName("Fatura")
        Fatura.resize(500, 405)
        self.centralwidget = QtWidgets.QWidget(Fatura)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(230, 20, 171, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 500, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(170, 50, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 140, 51, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(200, 220, 75, 41))
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 80, 61, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 150, 101, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 220, 61, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 150, 101, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 80, 61, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 220, 61, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(230, 150, 101, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 80, 61, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 220, 61, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.tab_4)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.tabWidget.addTab(self.tab_4, "")
        Fatura.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Fatura)
        self.statusbar.setObjectName("statusbar")
        Fatura.setStatusBar(self.statusbar)

        self.retranslateUi(Fatura)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Fatura)

    def retranslateUi(self, Fatura):
        _translate = QtCore.QCoreApplication.translate
        Fatura.setWindowTitle(_translate("Fatura", "Fatura Ödeme"))
        self.label_2.setText(_translate("Fatura", "Kurum Tipini Seçiniz"))
        self.comboBox.setItemText(0, _translate("Fatura", "Telefon"))
        self.comboBox.setItemText(1, _translate("Fatura", "Elektrik"))
        self.comboBox.setItemText(2, _translate("Fatura", "Su"))
        self.comboBox.setItemText(3, _translate("Fatura", "Doğalgaz"))
        self.label.setText(_translate("Fatura", "Tel No"))
        self.label_3.setText(_translate("Fatura", "Tutar"))
        self.pushButton.setText(_translate("Fatura", "ÖDE"))
        self.commandLinkButton.setText(_translate("Fatura", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Fatura", "Telefon"))
        self.label_5.setText(_translate("Fatura", "Abone No"))
        self.pushButton_2.setText(_translate("Fatura", "Sorgula"))
        self.label_6.setText(_translate("Fatura", "Ödenecek Tutar"))
        self.pushButton_3.setText(_translate("Fatura", "ÖDE"))
        self.commandLinkButton_2.setText(_translate("Fatura", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Fatura", "Elektrik"))
        self.label_7.setText(_translate("Fatura", "Abone No"))
        self.pushButton_4.setText(_translate("Fatura", "Sorgula"))
        self.pushButton_5.setText(_translate("Fatura", "ÖDE"))
        self.label_8.setText(_translate("Fatura", "Ödenecek Tutar"))
        self.commandLinkButton_3.setText(_translate("Fatura", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Fatura", "Su"))
        self.label_9.setText(_translate("Fatura", "Abone No"))
        self.pushButton_6.setText(_translate("Fatura", "Sorgula"))
        self.pushButton_7.setText(_translate("Fatura", "ÖDE"))
        self.label_10.setText(_translate("Fatura", "Ödenecek Tutar"))
        self.commandLinkButton_4.setText(_translate("Fatura", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Fatura", "Doğalgaz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fatura = QtWidgets.QMainWindow()
    ui = Ui_Fatura()
    ui.setupUi(Fatura)
    Fatura.show()
    sys.exit(app.exec_())
