# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Krediler.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kredi(object):
    def setupUi(self, Kredi):
        Kredi.setObjectName("Kredi")
        Kredi.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(Kredi)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 35, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(240, 31, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 95, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(250, 170, 141, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 240, 61, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(270, 90, 71, 51))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 30, 131, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(30, 105, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setGeometry(QtCore.QRect(230, 100, 131, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(240, 170, 101, 51))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 250, 61, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.widget, "")
        Kredi.setCentralWidget(self.centralwidget)

        self.retranslateUi(Kredi)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Kredi)

    def retranslateUi(self, Kredi):
        _translate = QtCore.QCoreApplication.translate
        Kredi.setWindowTitle(_translate("Kredi", "KREDİ İŞLEMLERİ"))
        self.label.setText(_translate("Kredi", "Kredi Türü :"))
        self.comboBox.setItemText(0, _translate("Kredi", "Seçiniz"))
        self.comboBox.setItemText(1, _translate("Kredi", "Teminata Göre"))
        self.comboBox.setItemText(2, _translate("Kredi", "Vadesine Göre"))
        self.comboBox.setItemText(3, _translate("Kredi", "Kurumsal Krediler"))
        self.label_2.setText(_translate("Kredi", "Tutar :"))
        self.label_3.setText(_translate("Kredi", "Taksit Seçenekleri :"))
        self.pushButton_3.setText(_translate("Kredi", "ÇEK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Kredi", "KREDİ ÇEKME"))
        self.label_4.setText(_translate("Kredi", "Kredilerim :"))
        self.label_5.setText(_translate("Kredi", "Taksit Tarihi :"))
        self.comboBox_5.setItemText(0, _translate("Kredi", "Ocak"))
        self.comboBox_5.setItemText(1, _translate("Kredi", "Şubat"))
        self.comboBox_5.setItemText(2, _translate("Kredi", "Mart"))
        self.comboBox_5.setItemText(3, _translate("Kredi", "Nisan"))
        self.comboBox_5.setItemText(4, _translate("Kredi", "Mayıs"))
        self.comboBox_5.setItemText(5, _translate("Kredi", "Haziran"))
        self.comboBox_5.setItemText(6, _translate("Kredi", "Temmuz"))
        self.comboBox_5.setItemText(7, _translate("Kredi", "Ağustos"))
        self.comboBox_5.setItemText(8, _translate("Kredi", "Eylül"))
        self.comboBox_5.setItemText(9, _translate("Kredi", "Ekim"))
        self.comboBox_5.setItemText(10, _translate("Kredi", "Kasım"))
        self.comboBox_5.setItemText(11, _translate("Kredi", "Aralık"))
        self.label_6.setText(_translate("Kredi", "Tutar :"))
        self.pushButton_4.setText(_translate("Kredi", "ÖDE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Kredi", "KREDİ ÖDEME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kredi = QtWidgets.QMainWindow()
    ui = Ui_Kredi()
    ui.setupUi(Kredi)
    Kredi.show()
    sys.exit(app.exec_())
