# created by beyza at 2019-12-1 10:30.
# email : beyzakarali4743@gmail.com


from PyQt5 import QtCore, QtGui, QtWidgets

##buton sıkıntılarını düzelt

class Ui_Donation(object):
    def __init__(self , prevWin  : QtWidgets.QMainWindow  = None ):
        self.winDonation = QtWidgets.QMainWindow()
        self.setupUi(self.winDonation)
        self.winDonation.show()
        self.prevWin = prevWin

    def change_page(self):
        self.tabWidget.setCurrentIndex(1)

    def passPrevWin(self):##########################################İŞE YARAMIYOR
        self.winDonation.close()
        self.prevWin.show()

    def setupUi(self, Donation):
        Donation.setObjectName("Donation")
        Donation.resize(489, 399)
        Donation.setMinimumSize(QtCore.QSize(489, 399))
        Donation.setMaximumSize(QtCore.QSize(489, 399))
        self.centralwidget = QtWidgets.QWidget(Donation)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 500, 411))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.commandLinkButton_7 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_7.setGeometry(QtCore.QRect(500, 400, 185, 41))
        self.commandLinkButton_7.setObjectName("commandLinkButton_7")
        self.commandLinkButton_8 = QtWidgets.QCommandLinkButton(self.widget)
        self.commandLinkButton_8.setGeometry(QtCore.QRect(370, 310, 111, 41))
        self.commandLinkButton_8.setStyleSheet("")
        self.commandLinkButton_8.setObjectName("commandLinkButton_8")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 221, 266))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget_3)
        self.commandLinkButton_2.setStyleSheet("")
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.verticalLayout_3.addWidget(self.commandLinkButton_2)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget_3)
        self.commandLinkButton.setStyleSheet("")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_3.addWidget(self.commandLinkButton)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget_3)
        self.commandLinkButton_3.setStyleSheet("")
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.verticalLayout_3.addWidget(self.commandLinkButton_3)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget_3)
        self.commandLinkButton_4.setStyleSheet("")
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.verticalLayout_3.addWidget(self.commandLinkButton_4)
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget_3)
        self.commandLinkButton_5.setStyleSheet("")
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.verticalLayout_3.addWidget(self.commandLinkButton_5)
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(self.verticalLayoutWidget_3)
        self.commandLinkButton_6.setStyleSheet("")
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")
        self.verticalLayout_3.addWidget(self.commandLinkButton_6)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(300, 310, 61, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton_9 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton_9.setGeometry(QtCore.QRect(390, 310, 91, 41))
        self.commandLinkButton_9.setStyleSheet("")
        self.commandLinkButton_9.setObjectName("commandLinkButton_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 10, 221, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setMouseTracking(True)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 10, 121, 173))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem18)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(0, 310, 191, 41))
        self.label_9.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../BmsLogo.png"))
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        Donation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Donation)
        self.statusbar.setObjectName("statusbar")
        Donation.setStatusBar(self.statusbar)

        self.retranslateUi(Donation)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Donation)
        Donation.setTabOrder(self.commandLinkButton_2, self.commandLinkButton)
        Donation.setTabOrder(self.commandLinkButton, self.commandLinkButton_3)
        Donation.setTabOrder(self.commandLinkButton_3, self.commandLinkButton_4)
        Donation.setTabOrder(self.commandLinkButton_4, self.commandLinkButton_5)
        Donation.setTabOrder(self.commandLinkButton_5, self.commandLinkButton_6)
        Donation.setTabOrder(self.commandLinkButton_6, self.commandLinkButton_8)
        Donation.setTabOrder(self.commandLinkButton_8, self.lineEdit)
        Donation.setTabOrder(self.lineEdit, self.lineEdit_2)
        Donation.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Donation.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Donation.setTabOrder(self.lineEdit_4, self.textEdit)
        Donation.setTabOrder(self.textEdit, self.pushButton)
        Donation.setTabOrder(self.pushButton, self.commandLinkButton_9)
        Donation.setTabOrder(self.commandLinkButton_9, self.commandLinkButton_7)

        self.commandLinkButton.clicked.connect(self.change_page)
        self.commandLinkButton_2.clicked.connect(self.change_page)
        self.commandLinkButton_3.clicked.connect(self.change_page)
        self.commandLinkButton_4.clicked.connect(self.change_page)
        self.commandLinkButton_5.clicked.connect(self.change_page)
        self.commandLinkButton_6.clicked.connect(self.change_page)
        self.commandLinkButton_7.clicked.connect(self.change_page)
        self.commandLinkButton_8.clicked.connect(self.passPrevWin)

    def retranslateUi(self, Donation):
        _translate = QtCore.QCoreApplication.translate
        Donation.setWindowTitle(_translate("Donation", "BAĞIŞ"))
        self.label.setText(_translate("Donation", "Bağış"))
        self.commandLinkButton_7.setText(_translate("Donation", "GERİ"))
        self.commandLinkButton_8.setText(_translate("Donation", "ANA MENÜ"))
        self.commandLinkButton_2.setText(_translate("Donation", "DARÜŞŞAFAKA"))
        self.commandLinkButton.setText(_translate("Donation", "AFAD"))
        self.commandLinkButton_3.setText(_translate("Donation", "KIZILAY"))
        self.commandLinkButton_4.setText(_translate("Donation", "LÖSEV"))
        self.commandLinkButton_5.setText(_translate("Donation", "TSK MEHMETÇİK VAKFI"))
        self.commandLinkButton_6.setText(_translate("Donation", "YEŞİLAY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Donation", "Seçim"))
        self.pushButton.setText(_translate("Donation", "GÖNDER"))
        self.commandLinkButton_9.setText(_translate("Donation", "GERİ"))
        self.label_2.setText(_translate("Donation", "Ad "))
        self.label_3.setText(_translate("Donation", "Soyad"))
        self.label_4.setText(_translate("Donation", "Tel.no"))
        self.label_6.setText(_translate("Donation", "Tutar"))
        self.label_5.setText(_translate("Donation", "Not"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Donation", "Bilgiler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DONATION = Ui_Donation()
    sys.exit(app.exec_())
