# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fatura.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bill(object):
    def __init__(self):
        self.winBill = QtWidgets.QMainWindow()
        self.setupUi(self.winBill)
        self.winBill.show()
    def setupUi(self, Bill):
        Bill.setObjectName("Bill")
        Bill.resize(500, 405)
        self.centralwidget = QtWidgets.QWidget(Bill)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 30, 171, 41))
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 500, 381))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(170, 50, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 120, 51, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(220, 220, 75, 41))
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 150, 101, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 80, 61, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 220, 61, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.tab_3)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(60, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(230, 150, 101, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 80, 61, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 220, 61, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.tab_4)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(60, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(60, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 80, 61, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 150, 101, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 220, 61, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(390, 270, 101, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(200, 30, 161, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        self.lineEdit_4.raise_()
        self.pushButton_3.raise_()
        self.commandLinkButton_2.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.tabWidget.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        Bill.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Bill)
        self.statusbar.setObjectName("statusbar")
        Bill.setStatusBar(self.statusbar)

        self.retranslateUi(Bill)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Bill)
        Bill.setTabOrder(self.comboBox, self.tabWidget)
        Bill.setTabOrder(self.tabWidget, self.lineEdit)
        Bill.setTabOrder(self.lineEdit, self.lineEdit_2)
        Bill.setTabOrder(self.lineEdit_2, self.pushButton)
        Bill.setTabOrder(self.pushButton, self.commandLinkButton)
        Bill.setTabOrder(self.commandLinkButton, self.lineEdit_11)
        Bill.setTabOrder(self.lineEdit_11, self.pushButton_2)
        Bill.setTabOrder(self.pushButton_2, self.lineEdit_4)
        Bill.setTabOrder(self.lineEdit_4, self.pushButton_3)
        Bill.setTabOrder(self.pushButton_3, self.commandLinkButton_2)
        Bill.setTabOrder(self.commandLinkButton_2, self.lineEdit_9)
        Bill.setTabOrder(self.lineEdit_9, self.pushButton_4)
        Bill.setTabOrder(self.pushButton_4, self.lineEdit_5)
        Bill.setTabOrder(self.lineEdit_5, self.pushButton_5)
        Bill.setTabOrder(self.pushButton_5, self.commandLinkButton_3)
        Bill.setTabOrder(self.commandLinkButton_3, self.lineEdit_10)
        Bill.setTabOrder(self.lineEdit_10, self.pushButton_6)
        Bill.setTabOrder(self.pushButton_6, self.lineEdit_7)
        Bill.setTabOrder(self.lineEdit_7, self.pushButton_7)
        Bill.setTabOrder(self.pushButton_7, self.commandLinkButton_4)

    def retranslateUi(self, Bill):
        _translate = QtCore.QCoreApplication.translate
        Bill.setWindowTitle(_translate("Bill", "Fatura Ödeme"))
        self.comboBox.setItemText(0, _translate("Bill", "Telefon"))
        self.comboBox.setItemText(1, _translate("Bill", "Su"))
        self.comboBox.setItemText(2, _translate("Bill", "Doğalgaz"))
        self.comboBox.setItemText(3, _translate("Bill", "Elektrik"))
        self.label.setText(_translate("Bill", "Tel No"))
        self.label_3.setText(_translate("Bill", "Tutar"))
        self.pushButton.setText(_translate("Bill", "ÖDE"))
        self.commandLinkButton.setText(_translate("Bill", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Bill", "Telefon"))
        self.pushButton_4.setText(_translate("Bill", "Sorgula"))
        self.pushButton_5.setText(_translate("Bill", "ÖDE"))
        self.label_8.setText(_translate("Bill", "Ödenecek Tutar"))
        self.commandLinkButton_3.setText(_translate("Bill", "GERİ"))
        self.label_12.setText(_translate("Bill", "TC  No"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Bill", "Su"))
        self.pushButton_6.setText(_translate("Bill", "Sorgula"))
        self.pushButton_7.setText(_translate("Bill", "ÖDE"))
        self.label_10.setText(_translate("Bill", "Ödenecek Tutar"))
        self.commandLinkButton_4.setText(_translate("Bill", "GERİ"))
        self.label_13.setText(_translate("Bill", "TC  No"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Bill", "Doğalgaz"))
        self.label_5.setText(_translate("Bill", "TC  No"))
        self.pushButton_2.setText(_translate("Bill", "Sorgula"))
        self.label_6.setText(_translate("Bill", "Ödenecek Tutar"))
        self.pushButton_3.setText(_translate("Bill", "ÖDE"))
        self.commandLinkButton_2.setText(_translate("Bill", "GERİ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Bill", "Elektrik"))
        self.label_2.setText(_translate("Bill", "Kurum Tipini Seçiniz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BİLL = Ui_Bill()
    sys.exit(app.exec_())
