

from PyQt5 import QtCore, QtGui, QtWidgets
from ControllerBMS.UserCls import User
from ModelBMS.database import Database as db

NEXT_TAB = 1

class Ui_SignUp(object):
    def __init__(self, prevWin = None):
        self.winRecord = QtWidgets.QMainWindow()
        self.setupUi(self.winRecord)
        self.winRecord.show()
        self.prevWin = prevWin
        self.onlineUser = User

    #Giris sayfasına aktarma
    def LogInPage (self):
        print("giris page....")
        self.winRecord.hide()
        self.prevWin.show()

    def changeTab(self):
        index = self.tabWidget.currentIndex()
        self.tabWidget.setCurrentIndex(index + NEXT_TAB)

    def insertUser(self):
        #eğer başarılı olursa giris_page çalıştır.
        userInfo = self.getUserInfo()
        for i in userInfo:
            print(i)
        self.onlineUser.insertUser(User, userInfo)
        print("insertUser function....")
        self.LogInPage()

    def getUserInfo(self):
        userInfo = []
        userInfo.append("2")
        userInfo.append(self.lineEdit.text())
        userInfo.append(self.lineEdit_2.text())
        userInfo.append(self.lineEdit_3.text())

         #yıl-ay-gün formatıyla olmalı
        userInfo.append(self.lineEdit_4.text())

        userInfo.append(self.lineEdit_5.text())
        userInfo.append(self.getGender())
        userInfo.append("photoname")
        userInfo.append(self.lineEdit_6.text())
        if self.lineEdit_7.text() == self.lineEdit_8.text():
            userInfo.append(self.lineEdit_7.text())

        return userInfo

    def getGender(self):
        if self.radioButton.isChecked() == True:
            return "K"
        else:
            return "E"



######################### SAYFA DÜZENİ ###########################
#Pyuic5 generator ile otomatik oluşturulmuştur.
    def setupUi(self, Record):
        Record.setObjectName("Record")
        Record.resize(500, 400)
        Record.setMinimumSize(QtCore.QSize(500, 400))
        Record.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(Record)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 500, 400))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 400))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.tabWidget.setIconSize(QtCore.QSize(100, 100))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(500, 400))
        self.tab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tab.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(300, 270, 61, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(380, 320, 101, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(250, 230, 82, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 230, 82, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 160, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 10, 160, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_2.addWidget(self.lineEdit_9)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(60, 220, 158, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setMinimumSize(QtCore.QSize(500, 400))
        self.tab_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tab_3.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(90, 160, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(90, 190, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(90, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 10, 181, 121))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../FOTO/images (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(270, 264))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 290, 75, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
     
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(250, 150, 160, 111))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_3.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_3.addWidget(self.lineEdit_8)
        self.tabWidget.addTab(self.tab_3, "")
        Record.setCentralWidget(self.centralwidget)
        self.actionmoney1 = QtWidgets.QAction(Record)
        self.actionmoney1.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../.designer/money.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmoney1.setIcon(icon1)
        self.actionmoney1.setObjectName("actionmoney1")

        self.retranslateUi(Record)
        self.tabWidget.setCurrentIndex(0)
        self.lineEdit_5.textEdited['QString'].connect(self.pushButton.click)
        self.lineEdit_4.textChanged['QString'].connect(self.pushButton.click)
        self.pushButton.clicked.connect(self.lineEdit_3.copy)
        QtCore.QMetaObject.connectSlotsByName(Record)
        Record.setTabOrder(self.tabWidget, self.lineEdit)
        Record.setTabOrder(self.lineEdit, self.lineEdit_2)
        Record.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Record.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Record.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Record.setTabOrder(self.lineEdit_5, self.lineEdit_9)
        Record.setTabOrder(self.lineEdit_9, self.radioButton)
        Record.setTabOrder(self.radioButton, self.radioButton_2)
        Record.setTabOrder(self.radioButton_2, self.pushButton)
        Record.setTabOrder(self.pushButton, self.commandLinkButton)
        Record.setTabOrder(self.commandLinkButton, self.pushButton_2)
        Record.setTabOrder(self.pushButton_2, self.lineEdit_6)
        Record.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Record.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        Record.setTabOrder(self.lineEdit_8, self.pushButton_3)
      


        self.commandLinkButton.clicked.connect(self.changeTab)
        self.pushButton_3.clicked.connect(self.insertUser)






    def retranslateUi(self, Record):
        _translate = QtCore.QCoreApplication.translate
        Record.setWindowTitle(_translate("Record", "KAYIT SAYFASI"))
        self.pushButton.setText(_translate("Record", "GİR"))
        self.commandLinkButton.setText(_translate("Record", "İLERLE"))
        self.radioButton.setText(_translate("Record", "KADIN"))
        self.radioButton_2.setText(_translate("Record", "ERKEK"))
        self.label.setText(_translate("Record", "Ad  "))
        self.label_2.setText(_translate("Record", "Soyad "))
        self.label_3.setText(_translate("Record", "T.C. No"))
        self.label_4.setText(_translate("Record", "Doğum Tarihi"))
        self.label_5.setText(_translate("Record", "Mail Adres"))
        self.label_10.setText(_translate("Record", "Tel no"))
        self.label_7.setText(_translate("Record", "Cinsiyet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Record", "KİŞİSEL BİLGİLER"))
        self.label_6.setText(_translate("Record", "Kullanıcı Adı"))
        self.label_8.setText(_translate("Record", "Şifre"))
        self.label_9.setText(_translate("Record", "Tekrar Şifre"))
        self.pushButton_3.setText(_translate("Record", "KAYDOL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Record", "KAYIT"))
        self.actionmoney1.setText(_translate("Record", "money1"))
        self.actionmoney1.setToolTip(_translate("Record", "image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RECORD = Ui_SignUp()
    sys.exit(app.exec_())
