#created by beyza at 2019-12-1 12:56.
# email : beyzakarali4743@gmail.com

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Credit(object):

    def __init__(self, prevWin : QtWidgets.QMainWindow = None):
        self.winCredit = QtWidgets.QMainWindow()
        self.setupUi(self.winCredit)
        self.winCredit.show()
        self.prevWin = prevWin

    def passPrevWin(self):
        self.winCredit.close()
        self.prevWin.show()


    def setupUi(self, Credit):
        Credit.setObjectName("Credit")
        Credit.resize(500, 400)
        Credit.setMinimumSize(QtCore.QSize(500, 400))
        Credit.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(Credit)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 361))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 240, 61, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(370, 330, 131, 41))
        self.commandLinkButton_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(270, 30, 160, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_3.addWidget(self.comboBox_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 30, 164, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.tabWidget.addTab(self.tab, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.widget.setObjectName("widget")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 250, 61, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 0, 160, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 10, 160, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(290, 150, 81, 61))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.widget, "")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(370, 360, 121, 41))
        self.commandLinkButton.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.commandLinkButton.setObjectName("commandLinkButton")
        Credit.setCentralWidget(self.centralwidget)

        self.retranslateUi(Credit)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Credit)
        Credit.setTabOrder(self.tabWidget, self.comboBox)
        Credit.setTabOrder(self.comboBox, self.comboBox_3)
        Credit.setTabOrder(self.comboBox_3, self.lineEdit)
        Credit.setTabOrder(self.lineEdit, self.pushButton_3)
        Credit.setTabOrder(self.pushButton_3, self.comboBox_4)
        Credit.setTabOrder(self.comboBox_4, self.comboBox_5)
        Credit.setTabOrder(self.comboBox_5, self.pushButton_4)
        Credit.setTabOrder(self.pushButton_4, self.commandLinkButton)
        Credit.setTabOrder(self.commandLinkButton, self.commandLinkButton_2)

        self.commandLinkButton_2.clicked.connect(self.passPrevWin)
        self.commandLinkButton.clicked.connect(self.passPrevWin)


    def retranslateUi(self, Credit):
        _translate = QtCore.QCoreApplication.translate
        Credit.setWindowTitle(_translate("Credit", "KREDİ İŞLEMLERİ"))
        self.pushButton_3.setText(_translate("Credit", "ÇEK"))
        self.commandLinkButton_2.setText(_translate("Credit", "ANAMENÜ"))
        self.comboBox.setItemText(0, _translate("Credit", "Seçiniz"))
        self.comboBox.setItemText(1, _translate("Credit", "Teminata Göre"))
        self.comboBox.setItemText(2, _translate("Credit", "Vadesine Göre"))
        self.comboBox.setItemText(3, _translate("Credit", "Kurumsal Krediler"))
        self.label.setText(_translate("Credit", "Kredi Türü :"))
        self.label_3.setText(_translate("Credit", "Taksit Seçenekleri :"))
        self.label_2.setText(_translate("Credit", "Tutar :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Credit", "KREDİ ÇEKME"))
        self.pushButton_4.setText(_translate("Credit", "ÖDE"))
        self.comboBox_5.setItemText(0, _translate("Credit", "Ocak"))
        self.comboBox_5.setItemText(1, _translate("Credit", "Şubat"))
        self.comboBox_5.setItemText(2, _translate("Credit", "Mart"))
        self.comboBox_5.setItemText(3, _translate("Credit", "Nisan"))
        self.comboBox_5.setItemText(4, _translate("Credit", "Mayıs"))
        self.comboBox_5.setItemText(5, _translate("Credit", "Haziran"))
        self.comboBox_5.setItemText(6, _translate("Credit", "Temmuz"))
        self.comboBox_5.setItemText(7, _translate("Credit", "Ağustos"))
        self.comboBox_5.setItemText(8, _translate("Credit", "Eylül"))
        self.comboBox_5.setItemText(9, _translate("Credit", "Ekim"))
        self.comboBox_5.setItemText(10, _translate("Credit", "Kasım"))
        self.comboBox_5.setItemText(11, _translate("Credit", "Aralık"))
        self.label_4.setText(_translate("Credit", "Kredilerim :"))
        self.label_5.setText(_translate("Credit", "Taksit Tarihi :"))
        self.label_6.setText(_translate("Credit", "Tutar :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Credit", "KREDİ ÖDEME"))
        self.commandLinkButton.setText(_translate("Credit", "ANA MENÜ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CREDIT = Ui_Credit()
    sys.exit(app.exec_())
