# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParaTransferi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoneyTransfer(object):
    def __init__(self):
        self.winMoneyTransfer = QtWidgets.QMainWindow()
        self.setupUi(self.winMoneyTransfer)
        self.winMoneyTransfer.show()

    def setupUi(self, MoneyTransfer):
        MoneyTransfer.setObjectName("MoneyTransfer")
        MoneyTransfer.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MoneyTransfer)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 401))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(120, 180, 71, 31))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 260, 271, 21))
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 320, 61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 100, 151, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(280, 20, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 231, 41))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 191, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(370, 330, 121, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 320, 61, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_5.setGeometry(QtCore.QRect(280, 20, 151, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 221, 31))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 260, 47, 13))
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 180, 71, 31))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 260, 271, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(20, 180, 111, 20))
        self.label_10.setObjectName("label_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 392, 251, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 231, 41))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(280, 100, 151, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(370, 330, 121, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(246, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")
        MoneyTransfer.setCentralWidget(self.centralwidget)

        self.retranslateUi(MoneyTransfer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MoneyTransfer)
        MoneyTransfer.setTabOrder(self.tabWidget, self.comboBox)
        MoneyTransfer.setTabOrder(self.comboBox, self.comboBox_2)
        MoneyTransfer.setTabOrder(self.comboBox_2, self.lineEdit)
        MoneyTransfer.setTabOrder(self.lineEdit, self.lineEdit_2)
        MoneyTransfer.setTabOrder(self.lineEdit_2, self.pushButton_3)
        MoneyTransfer.setTabOrder(self.pushButton_3, self.commandLinkButton_2)
        MoneyTransfer.setTabOrder(self.commandLinkButton_2, self.comboBox_5)
        MoneyTransfer.setTabOrder(self.comboBox_5, self.lineEdit_5)
        MoneyTransfer.setTabOrder(self.lineEdit_5, self.lineEdit_3)
        MoneyTransfer.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MoneyTransfer.setTabOrder(self.lineEdit_4, self.pushButton_4)
        MoneyTransfer.setTabOrder(self.pushButton_4, self.pushButton_5)

    def retranslateUi(self, MoneyTransfer):
        _translate = QtCore.QCoreApplication.translate
        MoneyTransfer.setWindowTitle(_translate("MoneyTransfer", "PARA TRANSFERİ"))
        self.pushButton_3.setText(_translate("MoneyTransfer", "GÖNDER"))
        self.label.setText(_translate("MoneyTransfer", "Gönderen Hesabınızı Seçiniz           :"))
        self.label_2.setText(_translate("MoneyTransfer", "Gönderilecek Hesabınızı Seçiniz       :"))
        self.label_4.setText(_translate("MoneyTransfer", "Not :"))
        self.label_3.setText(_translate("MoneyTransfer", "Tutarı Giriniz  :"))
        self.commandLinkButton_2.setText(_translate("MoneyTransfer", "ANA MENÜ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MoneyTransfer", "VİRMAN"))
        self.pushButton_4.setText(_translate("MoneyTransfer", "GÖNDER"))
        self.label_7.setText(_translate("MoneyTransfer", "Gönderen Hesabınızı Seçiniz           :"))
        self.label_9.setText(_translate("MoneyTransfer", "Not :"))
        self.label_10.setText(_translate("MoneyTransfer", "Tutarı Giriniz  :"))
        self.pushButton_5.setText(_translate("MoneyTransfer", "HESAPLARIM ARASI (VİRMAN) "))
        self.label_8.setText(_translate("MoneyTransfer", "Gönderilecek Hesap  IBAN     :"))
        self.commandLinkButton_3.setText(_translate("MoneyTransfer", "ANA MENÜ"))
        self.label_5.setText(_translate("MoneyTransfer", "TR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MoneyTransfer", "EFT/HAVALE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MONEYTRANSFER = Ui_MoneyTransfer()
    sys.exit(app.exec_())
