
# created by beyza at 2019-12-1 12:50.
# email : beyzakarali4743@gmail.com

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoneyTransfer(object):
    def __init__(self, prevWin : QtWidgets.QMainWindow  = None):
        self.winMoneyTransfer = QtWidgets.QMainWindow()
        self.setupUi(self.winMoneyTransfer)
        self.winMoneyTransfer.show()
        self.prevWin = prevWin

    def virman(self):
        pass

    def passPrevWin(self): 
        self.winMoneyTransfer.close()
        self.prevWin.show()

######################### SAYFA DÜZENİ ###########################
#Pyuic5 generator ile otomatik oluşturulmuştur.


    def setupUi(self, MoneyTransfer):
        MoneyTransfer.setObjectName("MoneyTransfer")
        MoneyTransfer.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MoneyTransfer)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 501, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 260, 61, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
    
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(269, 10, 201, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 233, 211))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 260, 61, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 392, 251, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(240, 80, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 10, 201, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 211, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.tabWidget.addTab(self.tab_2, "")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(370, 350, 121, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        MoneyTransfer.setCentralWidget(self.centralwidget)

        self.retranslateUi(MoneyTransfer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MoneyTransfer)
       
        MoneyTransfer.setTabOrder(self.comboBox, self.lineEdit)
        MoneyTransfer.setTabOrder(self.lineEdit, self.lineEdit_2)
        MoneyTransfer.setTabOrder(self.lineEdit_2, self.pushButton_3)
        MoneyTransfer.setTabOrder(self.pushButton_3, self.comboBox_5)
        MoneyTransfer.setTabOrder(self.comboBox_5, self.lineEdit_5)
        MoneyTransfer.setTabOrder(self.lineEdit_5, self.lineEdit_3)
        MoneyTransfer.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MoneyTransfer.setTabOrder(self.lineEdit_4, self.pushButton_4)
        MoneyTransfer.setTabOrder(self.pushButton_4, self.commandLinkButton_3)
        MoneyTransfer.setTabOrder(self.commandLinkButton_3, self.comboBox_2)
        MoneyTransfer.setTabOrder(self.comboBox_2, self.pushButton_5)
       
       #BAĞLANTILAR..
        self.commandLinkButton_3.clicked.connect(self.passPrevWin)

    def retranslateUi(self, MoneyTransfer):
        _translate = QtCore.QCoreApplication.translate
        MoneyTransfer.setWindowTitle(_translate("MoneyTransfer", "PARA TRANSFERİ"))
        self.pushButton_3.setText(_translate("MoneyTransfer", "GÖNDER"))
     
        self.label.setText(_translate("MoneyTransfer", "Gönderen Hesabınızı Seçiniz:"))
        self.label_2.setText(_translate("MoneyTransfer", "Gönderilecek Hesabınızı Seçiniz:"))
        self.label_3.setText(_translate("MoneyTransfer", "Tutarı Giriniz:"))
        self.label_4.setText(_translate("MoneyTransfer", "Not:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MoneyTransfer", "VİRMAN"))
        self.pushButton_4.setText(_translate("MoneyTransfer", "GÖNDER"))
        self.pushButton_5.setText(_translate("MoneyTransfer", "HESAPLARIM ARASI (VİRMAN) "))
        self.label_5.setText(_translate("MoneyTransfer", "TR"))
        self.label_7.setText(_translate("MoneyTransfer", "Gönderen Hesabınızı Seçiniz:"))
        self.label_8.setText(_translate("MoneyTransfer", "Gönderilecek Hesap  IBAN:"))
        self.label_10.setText(_translate("MoneyTransfer", "Tutarı Giriniz:"))
        self.label_9.setText(_translate("MoneyTransfer", "Not:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MoneyTransfer", "EFT/HAVALE"))
        self.commandLinkButton_3.setText(_translate("MoneyTransfer", "ANA MENÜ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MONEYTRANSFER = Ui_MoneyTransfer()
    sys.exit(app.exec_())
