# created by beyza at 2019-12-1 12:56.
# email : beyzakarali4743@gmail.com


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaxOfficial(object):
    def __init__(self , prevWin : QtWidgets.QMainWindow = None):

        self.winTaxOfficial = QtWidgets.QMainWindow()
        self.setupUi(self.winTaxOfficial)
        self.winTaxOfficial.show()
        self.prevWin = prevWin

    def passPrevWin(self): ################################## İŞE YARAMIYOR
        self.winTaxOfficial.close()
        self.prevWin.show()

    
    def setupUi(self, TaxOfficial):
        TaxOfficial.setObjectName("TaxOfficial")
        TaxOfficial.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(TaxOfficial)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 500, 380))
        self.toolBox.setMinimumSize(QtCore.QSize(1, 2))
        self.toolBox.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.toolBox.setSizeIncrement(QtCore.QSize(2, 0))
        self.toolBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toolBox.setLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 500, 326))
        self.page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.page.setObjectName("page")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 260, 51, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(270, 180, 111, 61))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.page)
        self.commandLinkButton.setGeometry(QtCore.QRect(410, 290, 81, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 0, 221, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 10, 160, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 158, 62))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.page_2.setObjectName("page_2")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(270, 180, 111, 61))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.page_2)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(410, 290, 81, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(209, 10, 221, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 160, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 260, 51, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.toolBox.addItem(self.page_2, "")
        TaxOfficial.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TaxOfficial)
        self.statusbar.setObjectName("statusbar")
        TaxOfficial.setStatusBar(self.statusbar)

        self.retranslateUi(TaxOfficial)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(TaxOfficial)
        TaxOfficial.setTabOrder(self.lineEdit, self.comboBox)
        TaxOfficial.setTabOrder(self.comboBox, self.pushButton)
        TaxOfficial.setTabOrder(self.pushButton, self.pushButton_2)
        TaxOfficial.setTabOrder(self.pushButton_2, self.lineEdit_2)
        TaxOfficial.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        TaxOfficial.setTabOrder(self.lineEdit_3, self.pushButton_3)
        TaxOfficial.setTabOrder(self.pushButton_3, self.pushButton_5)
        TaxOfficial.setTabOrder(self.pushButton_5, self.commandLinkButton_2)
        TaxOfficial.setTabOrder(self.commandLinkButton_2, self.commandLinkButton)

        self.commandLinkButton.clicked.connect(self.passPrevWin)
        self.commandLinkButton_2.clicked.connect(self.passPrevWin)

    def retranslateUi(self, TaxOfficial):
        _translate = QtCore.QCoreApplication.translate
        TaxOfficial.setWindowTitle(_translate("TaxOfficial", "Vergi Ve Resmi Kurum"))
        self.pushButton_2.setText(_translate("TaxOfficial", "ÖDE"))
        self.commandLinkButton.setText(_translate("TaxOfficial", "GERİ"))
        self.comboBox.setItemText(0, _translate("TaxOfficial", "Seçiniz"))
        self.comboBox.setItemText(1, _translate("TaxOfficial", "2019"))
        self.comboBox.setItemText(2, _translate("TaxOfficial", "2018"))
        self.comboBox.setItemText(3, _translate("TaxOfficial", "2017"))
        self.comboBox.setItemText(4, _translate("TaxOfficial", "2016"))
        self.comboBox.setItemText(5, _translate("TaxOfficial", "2015"))
        self.pushButton.setText(_translate("TaxOfficial", "Sorgula"))
        self.label.setText(_translate("TaxOfficial", "Plaka No"))
        self.label_3.setText(_translate("TaxOfficial", "Vergi Dönemi"))
        self.label_2.setText(_translate("TaxOfficial", "Ödenecek Tutar"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("TaxOfficial", "Motorlu Taşıtlar Vergisi"))
        self.label_7.setText(_translate("TaxOfficial", "Ödenecek Tutar"))
        self.commandLinkButton_2.setText(_translate("TaxOfficial", "GERİ"))
        self.pushButton_3.setText(_translate("TaxOfficial", "Sorgula"))
        self.label_5.setText(_translate("TaxOfficial", "Plaka No"))
        self.label_6.setText(_translate("TaxOfficial", "Tel no"))
        self.pushButton_5.setText(_translate("TaxOfficial", "ÖDE"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("TaxOfficial", "Trafik Cezası"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TAXOFFICIAL = Ui_TaxOfficial()
    sys.exit(app.exec_())
